server:
  port: 8080

spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.1.98:1433;databaseName=Demo;
    username: sa
    password: pass@word1

  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html

mybatis:
  mapper-locations: classpath:/mapper/*.xml
